version: "3.9"

services:
  fivem:
    build: ./fivem
    container_name: fivem-server
    env_file:
      - .env
    environment:
      - TERM=xterm
      - TXHOST_DATA_PATH=/opt/fivem/txData
      - TXHOST_TXA_PORT=40120
    ports:
      - "30120:30120/tcp"
      - "30120:30120/udp"
      - "40120:40120/tcp"
    volumes:
      - fivem_data:/opt/fivem/server-data
      - fivem_artifacts:/opt/fivem/server
      - fivem_txdata:/opt/fivem/txData
    restart: unless-stopped

  mariadb:
    image: mariadb:11
    container_name: fivem-db
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: fivem-phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    restart: unless-stopped

  backup:
    image: alpine
    container_name: fivem-backup
    depends_on:
      - mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - fivem_data:/volumes/fivem_data:ro
      - fivem_artifacts:/volumes/fivem_artifacts:ro
      - fivem_txdata:/volumes/fivem_txdata:ro
      - mariadb_data:/volumes/mariadb_data:ro
      - C:/fivem-backups:/backups
    entrypoint: >
      sh -c "
      apk add --no-cache mariadb-client tar;
      while true; do
        DATE=$$(date +%Y-%m-%d_%H-%M);

        echo 'Starting backup...';

        mysqldump -h mariadb -u root -p$$MYSQL_ROOT_PASSWORD --all-databases > /backups/db_$$DATE.sql;

        tar -czf /backups/fivem_server-data_$$DATE.tar.gz /volumes/fivem_data;
        tar -czf /backups/fivem_artifacts_$$DATE.tar.gz /volumes/fivem_artifacts;
        tar -czf /backups/fivem_txdata_$$DATE.tar.gz /volumes/fivem_txdata;

        find /backups -type f -mtime +7 -delete;

        echo 'Backup finished';

        sleep 86400;
      done
      "
    restart: unless-stopped

volumes:
  fivem_data:
  fivem_artifacts:
  fivem_txdata:
  mariadb_data:
